echo off
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 01 - Intro.mp3" 											 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 01 - Intro.mp4"   
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 02 - There Is So Much Bullshit.mp3" 						 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 02 - There Is So Much Bullshit.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 03 - Synonyms For Humbug.mp3" 							 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 03 - Synonyms For Humbug.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 04 - Short Of Lying.mp3" 								 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 04 - Short Of Lying.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 05 - Humbug Not Strickly A Lie.mp3" 						 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 05 - Humbug Not Strickly A Lie.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 06 - Wittgenstein Longfellow.mp3" 						 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 06 - Wittgenstein Longfellow.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 07 - Wittgenstein Combatting Insidious Nonsense.mp3" 	 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 07 - Wittgenstein Combatting Insidious Nonsense.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 08 - What Is Objectionable.mp3" 							 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 08 - What Is Objectionable.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 09 - The Point That Troubles Wittgenstein.mp3" 			 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 09 - The Point That Troubles Wittgenstein.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 10 - What Tends To Go On In A Bull Session.mp3" 			 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 10 - What Tends To Go On In A Bull Session.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 11 - The Term Bull.mp3" 									 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 11 - The Term Bull.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 12 - Hot Air.mp3" 										 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 12 - Hot Air.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 13 - Lying And Bluffing.mp3" 							 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 13 - Lying And Bluffing.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 14 - Our Attitude Towards Bullshit.mp3" 					 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 14 - Our Attitude Towards Bullshit.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 15 - Can't Lie Unless You Know The Truth.mp3" 			 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 15 - Can't Lie Unless You Know The Truth.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 16 - Bullshitters Further From Truth Than Liars.mp3" 	 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 16 - Bullshitters Further From Truth Than Liars.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 17 - Lack Of Connection Between Opions & Reality.mp3" 	 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 17 - Lack Of Connection Between Opions & Reality.mp4"
rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "Harry G. Frankfurt - 18 - Credits And Adds For Other Books On CD.mp3" 		 -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "Harry G. Frankfurt - 18 - Credits And Adds For Other Books On CD.mp4"

rem ffmpeg -loop 1 -i image.jpg -i audio.wav -c:v libx264 -tune stillimage -pix_fmt yuv420p -shortest out.mp4


rem echo file 'Harry G. Frankfurt - 01 - Intro.mp3' 								        > list.txt	
rem echo file 'Harry G. Frankfurt - 02 - There Is So Much Bullshit.mp3' 					>> list.txt	
rem echo file 'Harry G. Frankfurt - 03 - Synonyms For Humbug.mp3' 					        >> list.txt
rem echo file 'Harry G. Frankfurt - 04 - Short Of Lying.mp3' 								>> list.txt
rem echo file 'Harry G. Frankfurt - 05 - Humbug Not Strickly A Lie.mp3' 					>> list.txt	
rem echo file 'Harry G. Frankfurt - 06 - Wittgenstein Longfellow.mp3' 						>> list.txt
rem echo file 'Harry G. Frankfurt - 07 - Wittgenstein Combatting Insidious Nonsense.mp3' 	>> list.txt
rem echo file 'Harry G. Frankfurt - 08 - What Is Objectionable.mp3' 						>> list.txt	
rem echo file 'Harry G. Frankfurt - 09 - The Point That Troubles Wittgenstein.mp3' 			>> list.txt
rem echo file 'Harry G. Frankfurt - 10 - What Tends To Go On In A Bull Session.mp3' 		>> list.txt	
rem echo file 'Harry G. Frankfurt - 11 - The Term Bull.mp3' 								>> list.txt	
rem echo file 'Harry G. Frankfurt - 12 - Hot Air.mp3' 										>> list.txt
rem echo file 'Harry G. Frankfurt - 13 - Lying And Bluffing.mp3' 							>> list.txt
rem echo file 'Harry G. Frankfurt - 14 - Our Attitude Towards Bullshit.mp3' 				>> list.txt	
rem echo file 'Harry G. Frankfurt - 15 - Can_t Lie Unless You Know The Truth.mp3' 			>> list.txt
rem echo file 'Harry G. Frankfurt - 16 - Bullshitters Further From Truth Than Liars.mp3' 	>> list.txt
rem echo file 'Harry G. Frankfurt - 17 - Lack Of Connection Between Opions and Reality.mp3' 	>> list.txt
rem echo file 'Harry G. Frankfurt - 18 - Credits And Adds For Other Books On CD.mp3' 		>> list.txt
rem 
rem ffmpeg  -y -safe 0 -f concat -i list.txt -c copy long.mp3

rem ffmpeg -y -loop 1 -i "Harry G. Frankfurt.jpg" -i "long.mp3" -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest "long.mp4"

rem ffmpeg -y -r 1 -loop 1 -i "untitled.jpg" -i "Epidemioloog Dick Bijl over wachten met nemen van het vaccin - Nieuwsbericht - NPO Radio 2.mp3" -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -b:v 50K -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest -acodec mp2 -ac 1 -ar 22050 -ab 32k -r 1 "Epidemioloog Dick Bijl over wachten met nemen van het vaccin - Nieuwsbericht - NPO Radio 2.mp4"

ffmpeg -y -r 1 -loop 1 -i "download.png" -i "NA-1356-2021-06-17-Final.mp3" -c:v h264_nvenc -profile:v high -pix_fmt yuv420p -b:v 50K -bufsize 20M -bf:v 3 -preset slow -rc:v vbr_hq -rc-lookahead 32 -shortest  -r 1 -c:a copy "NA-1356-2021-06-17-Final.mp4"

pause



rem 